### ISSUE TITLE
App crashes on device rotate sometimes

### ISSUE THREAD

**Issue by wjdp** [nottinghamtec/JaVan#5]
_From @wjdp on July 11, 2016 20:14_

Hmm :confused: 

_Copied from original issue: wjdp/javan#5_

**Comment by wjdp** [comment]
```
07-12 01:01:36.612 28191-28191/uk.wjdp.javan E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: uk.wjdp.javan, PID: 28191
                                                               java.lang.RuntimeException: Unable to start activity ComponentInfo{uk.wjdp.javan/uk.wjdp.javan.activity.MainActivity}: android.view.InflateException: Binary XML file line #28: Error inflating class fragment
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
                                                                   at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3980)
                                                                   at android.app.ActivityThread.access$1000(ActivityThread.java:154)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1327)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:135)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5292)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
                                                                Caused by: android.view.InflateException: Binary XML file line #28: Error inflating class fragment
                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:763)
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                   at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916)
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:802)
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                   at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
                                                                   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                   at uk.wjdp.javan.activity.MainActivity.onCreate(MainActivity.java:27)
                                                                   at android.app.Activity.performCreate(Activity.java:5990)
                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420) 
                                                                   at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3980) 
                                                                   at android.app.ActivityThread.access$1000(ActivityThread.java:154) 
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1327) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                   at android.os.Looper.loop(Looper.java:135) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5292) 
                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                   at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699) 
                                                                Caused by: java.lang.IllegalStateException: Fragment uk.wjdp.javan.fragment.DriveFragment did not create a view.
                                                                   at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2145)
                                                                   at android.app.Activity.onCreateView(Activity.java:5328)
                                                                   at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:34)
                                                                   at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:79)
                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                                                                   at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916) 
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:802) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                   at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                                                                   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                   at uk.wjdp.javan.activity.MainActivity.onCreate(MainActivity.java:27) 
                                                                   at android.app.Activity.performCreate(Activity.java:5990) 
                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311) 
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420) 
                                                                   at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3980) 
                                                                   at android.app.ActivityThread.access$1000(ActivityThread.java:154) 
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1327) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                   at android.os.Looper.loop(Looper.java:135) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5292) 
                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                   at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699) 
```

**Comment by wjdp** [comment]
http://stackoverflow.com/questions/18307533/fragment-did-not-create-a-view
